/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#14201c',
        'ink-2': '#213029',
        'ink-soft': '#35453d',
        rice: '#eef5f1',
        'rice-deep': '#d9e6df',
        paper: '#f2f8f4',
        'paper-2': '#f6fbf8',
        kraft: '#dbe8e1',
        band: '#b6ccc1',
        line: '#a4c0b4',
        muted: '#6f8479',
        cinnabar: '#3f867d',
        'cinnabar-deep': '#215a52',
        'cinnabar-bright': '#579c92',
        gold: '#a98a45',
        'gold-bright': '#c6a558',
        'gold-pale': '#dccb92',
        amber2: '#cbb56a',
        jade: '#3c6b54',
        azurite: '#2e6273',
        alarm: '#b23a2e',
      },
      fontFamily: {
        serif: ['"Noto Serif SC"', 'serif'],
        sans: ['"Noto Sans SC"', 'sans-serif'],
        brush: ['"Ma Shan Zheng"', 'cursive'],
        scrawl: ['"Zhi Mang Xing"', 'cursive'],
      },
      boxShadow: {
        paper: '0 8px 24px rgba(30, 70, 60, 0.10)',
        'paper-lg': '0 24px 56px rgba(20, 55, 48, 0.20)',
        mount: '0 2px 0 0 #fff inset, 0 14px 34px -14px rgba(70,48,14,0.35)',
      },
      keyframes: {
        'shy-spin': { to: { transform: 'rotate(360deg)' } },
        'shy-wave': { '0%,100%': { transform: 'scaleY(0.28)' }, '50%': { transform: 'scaleY(1)' } },
        'shy-rise': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'none' } },
        'shy-pulse': { '0%,100%': { opacity: '0.35' }, '50%': { opacity: '1' } },
        drift: { '0%,100%': { transform: 'translateX(0)' }, '50%': { transform: 'translateX(-14px)' } },
        'seal-in': {
          from: { opacity: '0', transform: 'rotate(-18deg) scale(1.4)' },
          to: { opacity: '1', transform: 'rotate(-8deg) scale(1)' },
        },
      },
      animation: {
        'shy-spin': 'shy-spin 1s linear infinite',
        'shy-rise': 'shy-rise 0.5s ease both',
        'shy-pulse': 'shy-pulse 1s ease-in-out infinite',
        'shy-wave': 'shy-wave 0.6s ease-in-out infinite',
        drift: 'drift 18s ease-in-out infinite',
        'seal-in': 'seal-in .6s cubic-bezier(.2,.8,.2,1) both',
      },
    },
  },
  plugins: [],
}
